name: servicestack
version: 3.0.6
description: ServiceStack's convenience utils for developing Dart VM and flutter apps. Integrates with ServiceStack's Server features including ServiceClient, Error Handling and Validation
homepage: https://github.com/ServiceStack/servicestack-dart
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  http: ^1.5.0
  web: ^1.1.1
dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0