name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  publish:
    permissions:
      id-token: write  # Required for OIDC authentication with pub.dev
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

  release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

